# Generated by Django 5.1.2 on 2024-10-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0002_rename_created_date_geek_create_date_geek_play_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geek',
            old_name='play_date',
            new_name='start_date',
        ),
    ]
